name: Create development builds

on:
  pull_request:
    types: [labeled]
  issues:
    types: [labeled]

defaults:
  run:
    working-directory: ./apps/native

jobs:
  check_label:
    name: Check for devBuild label
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'devBuild' }}
    steps:
      - name: Label detected
        run: echo "devBuild label detected, proceeding with build"

  android_development_build:
    name: Build Android
    needs: check_label
    type: build
    params:
      platform: android
      profile: development
  # ios_device_development_build:
  #   name: Build iOS device
  #   type: build
  #   params:
  #     platform: ios
  #     profile: development
  # ios_simulator_development_build:
  #   name: Build iOS simulator
  #   type: build
  #   params:
  #     platform: ios
  #     profile: development-simulator
