name: Deploy to Internal Testing

on:
  push:
    branches: ['native']

defaults:
  
  run:
    working_directory: ./apps/native

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint

  get_android_build:
    name: Check for existing Android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: internal

  build_android:
    name: Build Android (Internal)
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: internal

  submit_android_build:
    name: Submit Android Build to Internal Track
    needs: [build_android]
    type: submit
    env:
      EXPO_DEBUG: "1"
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: internal

  publish_internal_update:
    name: Publish Internal Update
    needs: [submit_android_build]
    type: update
    params:
      branch: ${{ github.ref_name }}
