name: Publish preview update

on:
  push:
    branches: ['*']

defaults:
  run:
    working_directory: ./apps/native


jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
